name: Excavator

on:
  workflow_dispatch:
  schedule:
  - cron: '0 6 */3 * *'

jobs:
  excavate:
    name: Excavate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Excavate
      uses: ScoopInstaller/GithubActions@main
      env:
        GITH_EMAIL: younger321@foxmail.com
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SKIP_UPDATED: '1'
